### ISSUE TITLE
Use "榴槤/榴梿" in lieu of "榴蓮/榴莲".

### ISSUE THREAD

**Issue by ShikiSuen** [rime/brise#116]
其實我不知道東風破是否有這問題，傳到這邊也只是希望向 @kunki 求助在《現代漢語辭典第六版》和目前的《辭海》當中的「榴梿」詞條的照片擷圖或掃描擷圖而已（因為要向 Apple 提報其官方輸入法和 Siri 在這方面的 Bug…可惜這兩部辭典都不像教育部國語辭典那樣有線上版本、且 AppStore 的版本要麼是廣告詐欺應用、要麼就是舊版）。

這個 Issue 如果貴團隊已經確認早就修復或落實的話，請逕直關閉。謝謝。

**Comment by kunki** [comment]
"榴蓮/榴莲"和"榴槤/榴梿"竝存，"榴蓮/榴莲"詞頻較髙。
有何問題？

**Comment by ShikiSuen** [comment]
@kunki 首先，收回我一开始的请求（因为有志愿者提供了照片）。
**其次，回答您的问题：**
现在辞海第六版已经斧正了这个错误、不再承认「榴莲」；
![](https://cloud.githubusercontent.com/assets/3164826/17161799/a0f5affc-536d-11e6-8d46-f7d7d307269f.jpg)
同期，被用作高考书面用语圭臬的《现代汉语词典》也优先採「榴梿」。
![](https://cloud.githubusercontent.com/assets/3164826/17161811/abbd46f2-536d-11e6-92f9-6ba12732a18b.jpg)
鉴于这两个权威辞典现在转而拥护「榴梿」这个更符合字理的写法，于是我建议将「榴莲」的词频扣到最低（至少低于「榴梿」）。另：国民政府教育部标准国语辞典一直都在写「榴槤」，台湾繁体版维基百科也是写「榴槤」。

**Comment by kunki** [comment]
瞭解，既然兩地標準都以「榴槤」爲推薦詞形的話，那麼「榴槤」和「榴蓮」互換詞頻即可，但不必扣到最低。

**Comment by ShikiSuen** [comment]
謝謝。這討論串還是等你們解決之後自己關了吧。

**Comment by kunki** [comment]
等@lotem 来看看，他昨天新开了一个[仓库](https://github.com/rime/data-essay)，我不知道[原brise中的八股文](https://github.com/rime/brise/blob/master/essay.txt)的定位是什么。

**Comment by lotem** [comment]
brise 拆分完畢後， https://github.com/rime/brise/blob/master/essay.txt 會刪除。
修改可提交到[新倉庫](https://github.com/rime/data-essay)。

**Comment by kunki** [comment]
刪除後，essay的提交、修改歷史豈不是找不到了？
這部分歷史記錄需要時時參詳一番的。

**Comment by osfans** [comment]
@kunki 刪了之後，網頁上無法查到修改歷史了？git是可以的。

**Comment by lotem** [comment]
@kunki 我今晚回去處理一下
