### ISSUE TITLE
光劍注音輸入法對 Rime 源碼的挪用是被授權而為的嗎？

### ISSUE THREAD

**Issue by ShikiSuen** [rime/brise#129]
我一個多月前下載了光劍注音試用了一下，發現這玩意似乎就是加了殼的鼠鬚管、且用的還是不支持大千聲韻合擊的陳舊注音庫。

**Comment by Prcuvu** [comment]
感谢反馈。经过调查，光剑输入法的所有版本都是对RIME的封装，加入了一个功能更强大的设置界面。它的安卓和iOS版非常强大，有很好的联想功能。
不过确实有侵犯GPLv3（weasel、squirrel、brise）的嫌疑。

**Comment by ShikiSuen** [comment]
我真的很懷疑那玩意的「作者」身為台灣人居然會習慣那個版本的注音的詞庫。

**Comment by zaqzrh** [comment]
这个有windows版本吗？

**Comment by ShikiSuen** [comment]
@zaqzrh 
有，自己 Google 就能找到。

**Comment by lotem** [comment]
如果未遵守 GPL 許可證的條款，即爲未授權使用。
參見： https://zh.wikipedia.org/wiki/GNU通用公共许可证

作者曾來信通報該項目，我亦回信告知本作品的授權方式，敦促其使用 GPL 許可證再發佈。

**Comment by lotem** [comment]
我再談談對授權方式的一點淺見：
開源許可證是事先（發佈開源軟件時）已作出授權的，使用者（包括源碼的使用者）遵照許可證的條款使用則授權自動生效。反之，違背許可證的條款，則授權無效，即爲非授權使用。除非已取得過另外的授權許可。
