### ISSUE TITLE
增加GUI配置界面 Add GUI support for Configuration

### ISSUE THREAD

**Issue by suokunlong** [rime/brise#139]
当前，用户如果想要修改配置文件，只能去配置目录里手动修改文本文件，很多用户根本不懂这些语法规则。
添加一个gui界面用于配置，会让配置过程简化。比如，ibus-libpinyin就有gui界面。代码位于/usr/share/ibus-libpinyin/setup，是基于python2的，ibus-libpinyin-preferences.ui 是glade生成的。

**Comment by lotem** [comment]
有圖形化配置介面固然好。但是有幾個問題還沒有滿意的解法。

樓主提到的 ibus-libpinyin 我略有所知，其可配置的項目有限。
而設計一個與 YAML 配置文件功能等價的圖形介面是我無法想象的複雜工程，用起來也不會容易到哪裏去。其好處卻只是免去了學習 YAML 語法的些許負擔，這相對於開發這個複雜的圖形界面來說是極不划算的。
另一方面，YAML 配置文件主要是面向開發者，爲其定製輸入法提供最大的靈活性和開發效率。完成配置之後，對最終用戶應當是開箱即用的，並不要求每個用戶手動重複建立 YAML 配置的過程。

樓主提到的 ibus-libpinyin 我略有所知，但其採用的介面開發技術並不能涵蓋 Rime 所支持的所有平臺，如 Windows 和 macOS。更不會考慮爲受衆較少的單一平臺開發圖形介面。

**Comment by suokunlong** [comment]
使用rime的用户除了开发者，更多的将会是普通用户，他们根本不懂yaml，也没有时间去学习复杂的语法，也没有必要去学习。如果说rime定位的用户群只是开发者，那么我无话可说。100个人里面，可能只有2个开发者，其他的98个都是不懂编程的普通用户。

图形界面上根本没有必要涵盖所有的yaml中的配置选项，只需要满足最基本的配置功能就行了，如果用户需要更高级的配置，就去学习yaml然后手动修改配置文件。

**Comment by lotem** [comment]
配置這項功能，只面向開發者。
普通用戶只要關心怎麼打字就行了。

「最基本」的配置是什麼，對這個問題的理解因人而異。就一個人的經驗和具體需求來說，可以人爲把某些功能劃分爲基本的，其他是「沒必要」的；而放大到用戶全體，幾乎每項配置都有人點名需要，又當以什麼標準欽定「基本配置」和「高級配置」呢？
而我所認爲的「基本」，就是默認配置開箱即用，不需要用戶做任何配置。（如果用户需要更高级的配置，就去学习yaml然后手动修改配置文件。）

**Comment by suokunlong** [comment]
比如我是简体中文用户，安装后默认输入的是繁体中文。我想要切换为简体中文，试了好多常用的快捷键都不行，找配置界面又没有，正要放弃准备卸载，缺想着搜索一下，最后得知快捷键是Ctrl+'。我觉得5个输入建议太少了，而且想要横向显示输入建议。如果不去学习yaml，不去看github上的文档，就连用户配置文件在哪里都找不到。在输入法指示器那里链接一个“快速入门”或者帮助链接也好啊。

至于哪些是基本配置，完全可以参考其他输入法的选项清单。不需要征得每个用户的同意，您认为哪些是基本，哪些就是基本，不用涵盖很多。然后指出“更多高级配置，请自行参考说明文档编辑yaml文件”就够了。

**Comment by suokunlong** [comment]
rime的输入速度和建议精准率都很强大，我非常喜欢。只是觉得配置方面纯粹靠文本文件太复杂了，会吓跑很多普通用户。
