### ISSUE TITLE
丷（U+4E37）讀音是bā

### ISSUE THREAD

**Issue by zaqzrh** [rime/brise#97]
在unicode中：丷（U+4E37）kMandarin讀ha音，
但應為bā，地球拼音terra_pinyin.dict是對的。
unicode是編錯還是其他的原因呢？
,
再有一個「襨」dùi應為duì，kMandarin標錯了調。

**Comment by jakwings** [comment]
我建議不要盡信 Unihan 數據，沒有確切依據的都沒有太多參考價値，淪爲一家之言。多查字典看源流更有幫助。

Unihan 標錯調可以給他們反饋的。這裏好像沒有存放 Unihan 的數據吧？

**Comment by lotem** [comment]
Invalid issue.

**Comment by kunki** [comment]
Unihan 中來自kMandarin的數據極不可靠。比如「㤁」字（「忝」異體），kMandarin給的是一个野雞讀音miǎn。
在https://github.com/rime/brise/issues/4中我有將部分來自kMandarin的讀音導入了兩份拼音詞庫，看樣子得剝離出來。
