### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by blackangeldsf** [rime/brise#98]
git后，在源代码目录里面make,提示错误，
dsfsheng@linux-fds:~/brise/brise> make 
building rime data.
rime_deployer --build  /home/dsfsheng/brise/brise/output
E0823 11:34:23.742089 11527 config.cc:700] Error parsing YAML: yaml-cpp: error at line 0, column 0: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
E0823 11:34:23.797762 11527 config.cc:700] Error parsing YAML: yaml-cpp: error at line 0, column 0: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
E0823 11:34:23.804090 11527 config.cc:700] Error parsing YAML: yaml-cpp: error at line 0, column 0: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
E0823 11:34:23.804178 11527 deployment_tasks.cc:129] Error loading default config from '/home/dsfsheng/brise/brise/output/default.yaml'.
make: *** [all] 错误 1
dsfsheng@linux-fds:~/brise/brise>

**Comment by lotem** [comment]
我這兒無法重現，貼出代碼來看看吧，就這個文件
`/home/dsfsheng/brise/brise/output/default.yaml`

**Comment by lotem** [comment]
姑且認爲這個問題不再重現了。
